logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql: trace
      springframework: info
      flywaydb: debug
spring:
  data:
    rest:
      base-path: /api
      return-body-on-update: true
  jpa:
    hibernate:
      ddl-auto: update
# ignore null values
  jackson:
    default-property-inclusion: non_null
  application:
    name: spring-boot-startup
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/h2

server:
  use-forward-headers: true
  port: 8076

# this is required so that the oath filter takes precedence over the web security filter.
# otherwise the JSESSIONID cookie is enough to access the rest endpoints. with that the token is also needed
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    enabled: false

#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: tomcat
#    key-store-type: PKCS12
  #    key-alias: tomcat
management:
  endpoints:
    web:
      exposure:
        include: '*'
